### ISSUE TITLE
remove shadow ?

### ISSUE THREAD

**Issue by huitre39** [wezu/Avolition#1]
hello, i have question, 
how to remove the black background? (And extend the field of view)

**Comment by huitre39** [comment]
any help me ?

I just want to remove black background, To expand the field of view

**Comment by wezu** [comment]
Can you post a screenshot? I'm not sure what the problem is. There shouldn't be any black background.

**Comment by huitre39** [comment]
yes
![distant](https://cloud.githubusercontent.com/assets/22101022/19682518/310a468e-9aae-11e6-884a-2c9433322229.jpg)

I want to increase the viewing distance

**Comment by wezu** [comment]
Ok, I understand now. The easy way to do this is to change the attenuation of the point light, the default is (2, 0, 0.5) changing that to (2, 0, 0) should give you plenty of light. The tricky thing is making this change, it's somewhere in the spaghetti code of 'player.py'. I suggest using some sort of find-an-replace feature of any text editor and changing each "self.pLight.setAttenuation(Point3(2, 0, 0.5))" into "self.pLight.setAttenuation(Point3(2, 0, 0))" Do expect black artefacts.

**Comment by huitre39** [comment]
yes it's perfect !
thank you very much.
